module.exports = {
	RECEIVE_ALL_PHOTOS: "RECEIVE_ALL_PHOTOS",
	RECEIVE_PHOTO: "RECEIVE_PHOTO",
	UPDATE_PHOTO: "UPDATE_PHOTO",
	REMOVE_PHOTO: "REMOVE_PHOTO",
	PUBLIC_IMAGE_URL_RECEIVED: "PUBLIC_IMAGE_URL_RECEIVED",
	PRESIGNED_URL_RECEIEVED: "PRESIGNED_URL_RECEIEVED",
  CLEAR_UPLOAD_STORE: "CLEAR_UPLOAD_STORE"
};
